src/Entity/House.php
<?php

namespace App\Entity;

use App\Helper\AuthorInterface;
use App\Helper\AuthorTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use function Sodium\add;

/**
 * @ORM\Entity(repositoryClass="App\Repository\HouseRepository")
 */
class House implements AuthorInterface
{
    use AuthorTrait;
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", inversedBy="houses")
     */
    private $Users;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Room", mappedBy="house")
     */
    private $rooms;

    public function __construct()
    {
        $this->Users = new ArrayCollection();
        $this->rooms = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->Users;
    }

    public function addUser(User $user): self
    {
        if (!$this->Users->contains($user)) {
            $this->Users[] = $user;
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->Users->contains($user)) {
            $this->Users->removeElement($user);
        }

        return $this;
    }

    /**
     * @return Collection|Room[]
     */
    public function getRooms(): Collection
    {
        return $this->rooms;
    }

    public function addRoom(Room $room): self
    {
        if (!$this->rooms->contains($room)) {
            $this->rooms[] = $room;
            $room->setHouse($this);
        }

        return $this;
    }

    public function removeRoom(Room $room): self
    {
        if ($this->rooms->contains($room)) {
            $this->rooms->removeElement($room);
            // set the owning side to null (unless already changed)
            if ($room->getHouse() === $this) {
                $room->setHouse(null);
            }
        }

        return $this;
    }
}

src/Entity/Room.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RoomRepository")
 */
class Room
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\House", inversedBy="rooms")
     * @ORM\JoinColumn(nullable=false)
     */
    private $house;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Device", mappedBy="room", cascade={"persist"})
     */
    private $devices;

    public function __construct()
    {
        $this->devices = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getName();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getHouse(): ?House
    {
        return $this->house;
    }

    public function setHouse(?House $house): self
    {
        $this->house = $house;

        return $this;
    }

    /**
     * @return Collection|Device[]
     */
    public function getDevices(): Collection
    {
        return $this->devices;
    }

    public function addDevice(Device $device): self
    {
        if (!$this->devices->contains($device)) {
            $this->devices[] = $device;
            $device->setRoom($this);
        }

        return $this;
    }

    public function removeDevice(Device $device): self
    {
        if ($this->devices->contains($device)) {
            $this->devices->removeElement($device);
            // set the owning side to null (unless already changed)
            if ($device->getRoom() === $this) {
                $device->setRoom(null);
            }
        }

        return $this;
    }
}

src/Form/RoomType.php
<?php

namespace App\Form;

use App\Entity\Room;
use http\Client\Curl\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RoomType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $builder
            ->add('name')
            ->add('house')
            ->add('devices', CollectionType::class, [
                'label' => 'Устройства',
                'entry_type' => DeviceType::class,
                'entry_options' => ['label' => false],
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Room::class,
        ]);
    }
}

src/Controller/RoomController.php
<?php

namespace App\Controller;

use App\Entity\Room;
use App\Form\RoomType;
use App\Repository\RoomRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/room")
 */
class RoomController extends AbstractController
{
    /**
     * @Route("/", name="room_index", methods={"GET"})
     */
    public function index(RoomRepository $roomRepository): Response
    {
        return $this->render('room/index.html.twig', [
            'rooms' => $roomRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="room_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $room = new Room();
        $form = $this->createForm(RoomType::class, $room);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($room);
            $entityManager->flush();

            return $this->redirectToRoute('room_index');
        }

        return $this->render('room/new.html.twig', [
            'room' => $room,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="room_show", methods={"GET"})
     */
    public function show(Room $room): Response
    {
        return $this->render('room/show.html.twig', [
            'room' => $room,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="room_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Room $room): Response
    {
        $form = $this->createForm(RoomType::class, $room);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('room_index');
        }

        return $this->render('room/edit.html.twig', [
            'room' => $room,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="room_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Room $room): Response
    {
        if ($this->isCsrfTokenValid('delete'.$room->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($room);
            $entityManager->flush();
        }

        return $this->redirectToRoute('room_index');
    }
}

templates/room/_delete_form.html.twig
<form method="post" action="{{ path('room_delete', {'id': room.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ room.id) }}">
    <button class="btn">Delete</button>
</form>

templates/room/_form.html.twig
{{ form_start(form) }}
    <h3> Устройства</h3>
    <ul class="devices" data-prototype="{{ form_widget(form.devices.vars.prototype)|e('html_attr') }}">
        {% for dev in form.devices %}
            <li>{{ form_row(dev) }}</li>
        {% endfor %}
    </ul>
    {{ form_widget(form) }}
<button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}
<script>
    let $deviceCollectionHolder;
    let $addDeviceButton = $('<button type="button" class="add_device_link">Добавить устройство</button>');
    let $newDeviceLinkLi = $('<li></li>').append($addDeviceButton);

    jQuery(document).ready(function() {

        $deviceCollectionHolder = $('ul.devices');

        $deviceCollectionHolder.find('li').each(function() {
            addDeviceFormDeleteLink($(this));
        });

        $deviceCollectionHolder.append($newDeviceLinkLi);


        $deviceCollectionHolder.data('index', $deviceCollectionHolder.find(':input').length);

        $addDeviceButton.on('click', function(e) {
            addDeviceForm($deviceCollectionHolder, $newDeviceLinkLi);
        });
    });

    function addDeviceForm($collectionHolder, $newLinkLi) {

        let prototype = $collectionHolder.data('prototype');
        let index = $collectionHolder.data('index');
        let newForm = prototype;

        console.log(newForm);

        newForm = newForm.replace(/__name__/g, index);
        console.log(newForm);


        $collectionHolder.data('index', index + 1);

        let $newFormLi = $('<li></li>').append(newForm);
        $newLinkLi.before($newFormLi);
        addDeviceFormDeleteLink($newFormLi);
    }


    function addDeviceFormDeleteLink($deviceFormLi) {
        let $removeFormButton = $('<button type="button">Удалить устройство</button>');
        $deviceFormLi.append($removeFormButton);

        $removeFormButton.on('click', function(e) {
            $deviceFormLi.remove();
        });
    }
</script>

templates/room/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Редактировать комнату{% endblock %}

{% block body %}
    <h1>Редактировать комнату</h1>
    {% if app.user in room.house.users%}
    {{ include('room/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="actions" href="{{ path('room_index') }}">Назад к списку</a>

    {{ include('room/_delete_form.html.twig') }}
    {% else %}
        <div>Вы не являетесь владельцем данной комнаты</div>
    {% endif %}
{% endblock %}

templates/room/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Мои комнаты{% endblock %}

{% block body %}
    <h1>Мои комнаты</h1>
    {% if app.user%}
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Название</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
        {% for room in rooms if app.user in room.house.users %}
            <tr>
                <td>{{ room.id }}</td>
                <td>{{ room.name }}</td>
                <td>
                    <a href="{{ path('room_show', {'id': room.id}) }}">показать</a>
                    <a href="{{ path('room_edit', {'id': room.id}) }}">редактировать</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">У вас нет комнаты</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="actions" href="{{ path('room_new') }}">Создать новую</a>
    <a class="actions" href="{{ path('home') }}">На главную</a>
    {% else %}
        <div>Войдите чтобы просмотреть ваши комнаты</div>
    {% endif %}
{% endblock %}

templates/room/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Создать новую комнату{% endblock %}

{% block body %}
    <h1>Создать новую комнату</h1>
    {% if app.user %}
    {{ include('room/_form.html.twig') }}

    <a class="actions" href="{{ path('room_index') }}">Назад к списку</a>
    {% else %}
        <div>Войдите чтобы создать комнату</div>
    {% endif %}
{% endblock %}

templates/room/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Комната{% endblock %}

{% block body %}
    <h1>Комната</h1>
    {% if app.user in room.house.users%}
    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ room.id }}</td>
            </tr>
            <tr>
                <th>Название</th>
                <td>{{ room.name }}</td>

            </tr>
            <tr>
                <th>Устройства</th>
                <td>{% for dev in room.devices %}<a href="{{ path('device_show', {'id': dev.id}) }}">{{  dev.name }}</a> {% endfor %}</td>
            </tr>
        </tbody>
    </table>

    <a class="actions" href="{{ path('room_index') }}">back to list</a>

    <a class="actions" href="{{ path('room_edit', {'id': room.id}) }}">edit</a>

    {{ include('room/_delete_form.html.twig') }}
    {% else %}
        <div>Вы не являетесь владельцем данной комнаты</div>
    {% endif %}
{% endblock %}