src/Entity/DeviceType.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DeviceTypeRepository")
 */
class DeviceType
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="deviceTypes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    public function __toString()
    {
        return $this->getName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }
}

src/Form/DeviceTypeType.php
<?php

namespace App\Form;

use App\Entity\DeviceType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DeviceTypeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('User')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => DeviceType::class,
        ]);
    }
}

src/Controller/DeviceTypeController.php
<?php

namespace App\Controller;

use App\Entity\DeviceType;
use App\Form\DeviceTypeType;
use App\Repository\DeviceTypeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/device_type")
 */
class DeviceTypeController extends AbstractController
{
    /**
     * @Route("/", name="device_type_index", methods={"GET"})
     */
    public function index(DeviceTypeRepository $deviceTypeRepository): Response
    {
        return $this->render('device_type/index.html.twig', [
            'device_types' => $deviceTypeRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="device_type_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $deviceType = new DeviceType();
        $form = $this->createForm(DeviceTypeType::class, $deviceType);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($deviceType);
            $entityManager->flush();

            return $this->redirectToRoute('device_type_index');
        }

        return $this->render('device_type/new.html.twig', [
            'device_type' => $deviceType,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="device_type_show", methods={"GET"})
     */
    public function show(DeviceType $deviceType): Response
    {
        return $this->render('device_type/show.html.twig', [
            'device_type' => $deviceType,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="device_type_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, DeviceType $deviceType): Response
    {
        $form = $this->createForm(DeviceTypeType::class, $deviceType);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('device_type_index');
        }

        return $this->render('device_type/edit.html.twig', [
            'device_type' => $deviceType,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="device_type_delete", methods={"DELETE"})
     */
    public function delete(Request $request, DeviceType $deviceType): Response
    {
        if ($this->isCsrfTokenValid('delete'.$deviceType->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($deviceType);
            $entityManager->flush();
        }

        return $this->redirectToRoute('device_type_index');
    }
}

templates/device_type/_delete_form.html.twig
<form method="post" action="{{ path('device_type_delete', {'id': device_type.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ device_type.id) }}">
    <button class="btn">Delete</button>
</form>

templates/device_type/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/device_type/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit DeviceType{% endblock %}

{% block body %}
    <h1>Редактировать тип устройств</h1>
    {% if app.user%}
    {{ include('device_type/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('device_type_index') }}">назад к списку</a>

    {{ include('device_type/_delete_form.html.twig') }}
    {% else %}
        <div>Войдите чтобы просмотреть ваши устройства</div>
    {% endif %}
{% endblock %}

templates/device_type/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}DeviceType index{% endblock %}

{% block body %}
    <h1>Типы устройств</h1>
    {% if app.user%}
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Название</th>
                <th>действия</th>
            </tr>
        </thead>
        <tbody>
        {% for device_type in device_types %}
            <tr>
                <td>{{ device_type.id }}</td>
                <td>{{ device_type.name }}</td>
                <td>
                    <a href="{{ path('device_type_show', {'id': device_type.id}) }}">показать</a>
                    <a href="{{ path('device_type_edit', {'id': device_type.id}) }}">редактировать</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">нет записей</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="actions" href="{{ path('device_type_new') }}">Создать</a>
        <a class="actions" href="{{ path('home') }}">На главную</a>
    {% else %}
        <div>Войдите чтобы просмотреть ваши устройства</div>
    {% endif %}
{% endblock %}

templates/device_type/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Новый тип{% endblock %}

{% block body %}
    <h1>Создать новый тип устройств</h1>
    {% if app.user %}
    {{ include('device_type/_form.html.twig') }}

    <a href="{{ path('device_type_index') }}">назад к списку</a>
    {% else %}
    <div>Вы не являетесь владельцем данного дома</div>
    {% endif %}
{% endblock %}

templates/device_type/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Типы устройств{% endblock %}

{% block body %}
    <h1>Типы устройств</h1>
    {% if app.user%}
    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ device_type.id }}</td>
            </tr>
            <tr>
                <th>Название</th>
                <td>{{ device_type.name }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('device_type_index') }}">назад к списку</a>

    <a href="{{ path('device_type_edit', {'id': device_type.id}) }}">редактировать</a>

    {{ include('device_type/_delete_form.html.twig') }}
    {% else %}
        <div>Вы не являетесь владельцем данного дома</div>
    {% endif %}
{% endblock %}